# Generated by Django 4.2.5 on 2023-09-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinorder',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.good'),
        ),
        migrations.AlterField(
            model_name='goodinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.order'),
        ),
    ]
